In [ ]:
import torch
import torch.nn as nn

# Tensors in PyTorch

In [ ]:
tensor_1d = torch.tensor([1, 2, 3])
print("1D Tensor (Vector):")
print(tensor_1d, end="\n\n")

tensor_2d = torch.tensor([[1, 2], [3, 4]])
print("2D Tensor (Matrix):")
print(tensor_2d, end="\n\n")

random_tensor = torch.rand(2, 3)
print("Random Tensor (2x3):")
print(random_tensor, end="\n\n")

zeros_tensor = torch.zeros(2, 3)
print("Zeros Tensor (2x3):")
print(zeros_tensor, end="\n\n")

ones_tensor = torch.ones(2, 3)
print("Ones Tensor (2x3):")
print(ones_tensor)

1D Tensor (Vector):
tensor([1, 2, 3])

2D Tensor (Matrix):
tensor([[1, 2],
        [3, 4]])

Random Tensor (2x3):
tensor([[0.6981, 0.5817, 0.2110],
        [0.0020, 0.8835, 0.8303]])

Zeros Tensor (2x3):
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones Tensor (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])


# Tensor Operations in PyTorch

In [3]:
tensor = torch.tensor([[1, 2], [3, 4], [5, 6]])

element = tensor[1, 0]
print(f"Indexed Element (Row 1, Column 0): {element}", end="\n\n")  
slice_tensor = tensor[:2, :]
print(f"Sliced Tensor (First two rows): \n{slice_tensor}", end="\n\n")

reshaped_tensor = tensor.view(2, 3)
print(f"Reshaped Tensor (2x3): \n{reshaped_tensor}")


Indexed Element (Row 1, Column 0): 3

Sliced Tensor (First two rows): 
tensor([[1, 2],
        [3, 4]])

Reshaped Tensor (2x3): 
tensor([[1, 2, 3],
        [4, 5, 6]])


# Broadcasting, Matrix Multiplication

In [4]:
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor_b = torch.tensor([[10, 20, 30]]) 

broadcasted_result = tensor_a + tensor_b 
print(f"Broadcasted Addition Result: \n{broadcasted_result}", end="\n\n")

matrix_multiplication_result = torch.matmul(tensor_a, tensor_a.T)
print(f"Matrix Multiplication Result (tensor_a * tensor_a^T): \n{matrix_multiplication_result}")

Broadcasted Addition Result: 
tensor([[11, 22, 33],
        [14, 25, 36]])

Matrix Multiplication Result (tensor_a * tensor_a^T): 
tensor([[14, 32],
        [32, 77]])


# GPU Acceleration with PyTorch

In [5]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {device}')

Using device: cuda


In [6]:
tensor_size = (10000, 10000)  
a = torch.randn(tensor_size, device=device)  
b = torch.randn(tensor_size, device=device)  

c = a + b  

print("Result shape (moved to CPU for printing):", c.cpu().shape)

print("Current GPU memory usage:")
print(f"Allocated: {torch.cuda.memory_allocated(device) / (1024 ** 2):.2f} MB")
print(f"Cached: {torch.cuda.memory_reserved(device) / (1024 ** 2):.2f} MB")


Result shape (moved to CPU for printing): torch.Size([10000, 10000])
Current GPU memory usage:
Allocated: 1146.00 MB
Cached: 1146.00 MB


# Building and Training Neural Networks with PyTorch

In [7]:
class SimpleNeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2, 4)
        self.fc2 = nn.Linear(4, 1)
        
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

In [8]:
# class SimpleNeuralNetwork(nn.Module):
#     def __init__(self):
#         super().__init__()
#         self.fc1 = nn.Linear(2, 4)
#         self.fc2 = nn.Linear(4, 1)
        
#     def forward(self, x):
#         return self.fc2(torch.relu(self.fc1(x)))

In [9]:
model = SimpleNeuralNetwork()
loss_function = nn.MSELoss()

In [10]:
X_train = torch.tensor([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]]) 
y_train = torch.tensor([[0.0], [1.0], [1.0], [0.0]])

In [11]:
import torch.optim as optim

optimizer = optim.SGD(model.parameters(), lr=0.1)

In [ ]:
for epoch in range(100):
    model.train()
    
    output = model(X_train)
    loss = loss_function(output, y_train)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if (epoch+1) % 10 == 0:
        print(f'Epoch [{epoch + 1}/100], Loss: {loss.item():.4f}')

Epoch [10/200], Loss: 0.1567
Epoch [20/200], Loss: 0.1481
Epoch [30/200], Loss: 0.1390
Epoch [40/200], Loss: 0.1264
Epoch [50/200], Loss: 0.1106
Epoch [60/200], Loss: 0.0922
Epoch [70/200], Loss: 0.0718
Epoch [80/200], Loss: 0.0531
Epoch [90/200], Loss: 0.0392
Epoch [100/200], Loss: 0.0261
Epoch [110/200], Loss: 0.0179
Epoch [120/200], Loss: 0.0116
Epoch [130/200], Loss: 0.0075
Epoch [140/200], Loss: 0.0046
Epoch [150/200], Loss: 0.0029
Epoch [160/200], Loss: 0.0017
Epoch [170/200], Loss: 0.0010
Epoch [180/200], Loss: 0.0007
Epoch [190/200], Loss: 0.0004
Epoch [200/200], Loss: 0.0002


In [15]:
model.eval()
with torch.no_grad():
    test_data = torch.tensor([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])
    predictions = model(test_data)
    print(f'Predictions:\n{predictions}')

Predictions:
tensor([[0.0137],
        [0.9837],
        [0.9837],
        [0.0137]])
